### ISSUE TITLE
Issue with cloudfront/s3 url

### ISSUE THREAD

**Issue by tuananh** [tripviss/image-resizer#34]
I've edit the environment to include

```
EXTERNAL_SOURCE_VF='http://www.cfmedia.vfmleonardo.com/'
```
However, whenever I try loading an image, i got 500 error, `The specified key does not exist.` (looks like the original is on cloudfront/s3).

```mydomain.com/evf/imageRepo/4/0/55/359/440/ROY.44A_H.jpg```

Example of said image url: `http://www.cfmedia.vfmleonardo.com/imageRepo/4/0/55/359/440/ROY.44A_H.jpg`

I do not have control over this image / url.

**Comment by teohhanhui** [comment]
```env
EXTERNAL_SOURCE_VF='http://www.cfmedia.vfmleonardo.com/'
```

You should not include the trailing slash in the prefix. (We cannot change this now without breaking BC.)

See https://github.com/tripviss/image-resizer/blob/d226667cb948f2570b96e25585f9cbc6bf33cfd3/src/streams/sources/external.js#L64

p/s: The external source filter does not care about where the original image is hosted on, because it only sends a HTTP GET to the specified URL.

**Comment by tuananh** [comment]
@teohhanhui ah this fixed it for me. Many thanks.
